baseURL: "https://ajarmusch.github.io"
title: Jarmusch A. M. 
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Publications
                  url: publications
                  weight: 1
                - name: Github
                  url: https://github.com/ajarmusch
                - name: LinkedIn
                  url: https://www.linkedin.com/in/aaron-jarmusch/

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Aaron M. Jarmusch"
    author: Me
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["MiEmoji.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        # buttons:
        #     - name: Archives
        #       url: archives
        #     - name: Tags
        #       url: tags

    homeInfoParams:
        Title: "hey there!"
        Content: >
            I'm Aaron, I enjoy High-Performance Computing and building software for parallel computing. Recently I found building compilers and LLM's for daily use fun. I've contributed to a growing number of open-source projects.
            
            - Oh also, starting a blog to follow my learning expierence in HPC and software engineering.
            
            - See ya 😉


    socialIcons:
        - name: github
          url: "https://github.com/ajarmusch"
        # - name: KoFi
        #   url: "https://ko-fi.com/adityatelange"
        # - name: Rss
        #   url: "index.xml"

    editPost:
        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link


markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: true
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: true
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
